### ISSUE TITLE
[Bug]: Cookie not set

### ISSUE THREAD

**Issue by ahrzeroday** [kawacode/gorequest#8]
### Version of the Library

1.0.13

### What happened?

Hello,
First of all sorry for my Bad English
I use this code for testing :
`

	var bot gostruct.BotData
	bot.HttpRequest.Request.URL = "https://httpbin.org/cookies/set?test=123&test2=456&test3=789"
	bot.HttpRequest.Request.Method = "GET"
	bot.HttpRequest.Request.Protocol = "2"
	bot.HttpRequest.Request.ReadResponseBody = true
	bot.HttpRequest.Request.ReadResponseCookies = true
	bot.HttpRequest.Request.ReadResponseHeaders = true
	bot.HttpRequest.Request.MaxRedirects = "2"
	bot.HttpRequest.Request.Client = *gotools.GetHelloClient("HelloChrome_107")
	bot.HttpRequest.Request.Headers = map[string]string{
		"Connection":                "keep-alive",
		"sec-ch-ua":                 "\" Not A;Brand\";v=\"99\", \"Chromium\";v=\"101\", \"Opera\";v=\"87\"",
		"sec-ch-ua-mobile":          "?0",
		"sec-ch-ua-platform":        "\"Windows\"",
		"Upgrade-Insecure-Requests": "1",
		"User-Agent":                useragent,
		"Accept":                    "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9",
		"Sec-Fetch-Site":            "none",
		"Sec-Fetch-Mode":            "navigate",
		"Sec-Fetch-User":            "?1",
		"Sec-Fetch-Dest":            "document",
		"Accept-Language":           "en-US,en;q=0.9",
		"Accept-Encoding":           "gzip, deflate",
	}
	gorequest.HttpRequest(&bot)
	response := bot.HttpRequest.Response.Source
	for k, v := range bot.HttpRequest.Request.Headers {
		println(k, ":	", v)
	}
	println(response)
`

but no cookie set and also when i print bot.HttpRequest.Response.Headers show me only last Cookie-Set Header

**Comment by kawacode** [comment]
There is no bug at all.
Somehow It is not redirecting to with the cookies, which means the server does not get any cookies. To solve it you need to redirect the cookies manually. BTW the cookies are not stored in the header list. They are stored in the Cookie list. Use following code for getting the cookies:
```go
for k, v := range bot.HttpRequest.Response.Cookies {
		println(k, ":	", v)
}
```
Now send a new request with the cookies you got. It should fix your problem.
